### ISSUE TITLE
Lab06

### ISSUE THREAD

**Issue by jumphrey77** [MicrosoftLearning/20537-Configuring-and-Operating-a-Hybrid-Cloud-with-Microsoft-Azure-Stack#10] opened 2018-03-02 00:53 UTC
CustomerScriptExtension (installation of SCOM) fails in Lab #6 and therefore you can't do lab 8.  I don't think the blob https://samslmedia.blob.local.azurestack.external/powershell/Install-SCOM.ps1 exists.

**Comment by JustinKimber** [comment] 2018-03-23 17:53
We have a fix for this now. It was caused by an online resource no longer available. Please see the Error Log for 20537A. The fix will be incorporated into the 20537B build of the course.

**Closed by JustinKimber** 2018-03-23 17:53 UTC
